### ISSUE TITLE
Problem with format of Guides

### ISSUE THREAD

**Issue by ClarkInAz** [sparkfun/SparkFun_Qwiic_CO2_Sensor_XENSIV_PAS#1]
### Subject of the issue
Problem with overall format for Guides

### Your workbench
Firefox web browser on OSX
### Steps to reproduce
Look through the original guide by clicking on the "Getting Started" guide on https://www.sparkfun.com/products/22956
### Expected behavior
A clear explaination of HOW to get to the next page after the "background info" stuff.

### Actual behavior
FORCES first time user of this new Guide format to GUESS how to get to actual info.  Go look at one of the older "Getting Started" guides -- it's VERY CLEAR how to get to the next page!

For example, https://learn.sparkfun.com/tutorials/sparkfun-gps-rtk-dead-reckoning-zed-f9r-hookup-guide
It's BLATANTLY CLEAR how to get to the next page!

**Comment by gigapod** [comment]
Hi @ClarkInAz,

Like many companies/individuals ([Arduino for example](https://arduino.github.io/arduino-cli/0.35/)) in the development board space, we’re moving to host our hookup guides/documentation on GitHub pages – using [Material MKDocs](https://squidfunk.github.io/mkdocs-material/) to generate our content. 

The transition to a GitHub Pages solution provides SparkFun better tools to generate our documentation/content and more importantly reinforces our continued engagement and cooperation with the community as a whole – enabling rapid integration of community feedback, suggestions, and edits. This was difficult to impossible with our older system. 

The documentation and content teams spent considerable effort in developing our new solution and are continuing to improve it going forward.

While the new solution does provide a “next page” indicator/link at the bottom of our documentation pages, your feedback is helpful for the teams as the continue to review our solution.

-Kirk
