### ISSUE TITLE
Difficulty of submitting comment or issue with the new format

### ISSUE THREAD

**Issue by ClarkInAz** [sparkfun/SparkFun_Qwiic_CO2_Sensor_XENSIV_PAS#2]
### Subject of the issue
Although the new format allows ADVANCED users to actually do something about problems, it needlessly complicates things for the NOVICE user.

### Your workbench
Firefox on OSX

### Steps to reproduce
Try to submit an issue WITHOUT being logged into GitHub
### Expected behavior
There should be a way to submit an issue and/or ccomment WITHOUT having to have a GitHub account.  Although I can see the requirement to have a SparkFun account to add an issue and/or comment on the "Getting Started" guides for SparkFun products, layering on the need for a GitHub account will scare off MANY "novice" users!

Compare the "Comments" submission for the old format of "Getting Started" guides, e.g. https://learn.sparkfun.com/tutorials/sparkfun-gps-rtk-dead-reckoning-zed-f9r-hookup-guide

BTW, I _DO_ like the idea of allowing "more advanced" users the ability to make corrections/additions, and CAN see the need to have the GitHub login for that purpose.

### Actual behavior
Excess B.S./"red tape" to be able to submit a comment/issue.

**Comment by gigapod** [comment]
Hi @ClarkInAz ,

Thanks for your feedback. As our team continues to learn and develop our content in this new system, we’ll look into methods that improve our customer experience. 
The github login requirement is a side-effect of our move to Github Pages. As noted, this is not ideal for our customers not on github. Unclear if we could link to a SparkFun account in this system, but our traditional support solutions (email, and forums) are still available.
GitHub Pages provides greatly improved tools for our content team, and a vast improvement in identifying, tracking, and correcting issues in our content. Issues in our old system were often forgotten in a sea of individual posts – now they are unified in one backlog. 
The team will continue to look improve our content solutions and appreciate the feedback you’re provided. 

Regards,
-Kirk
