### ISSUE TITLE
Missing item in "Hardware Overview"

### ISSUE THREAD

**Issue by ClarkInAz** [sparkfun/SparkFun_Qwiic_CO2_Sensor_XENSIV_PAS#3]
### Subject of the issue
In the "Hardware Overview", under "Solder Jumpers", the I2C jumper is listed, but there's no explaination of what it does.

### Your workbench
Firefox on OSX

### Steps to reproduce
Read the "Solder Jumpers" section of the Guide.
### Expected behavior
The purpose of each of the four jumpers, PWR, PSEL, PWM, and I2C should have its own bullet describing what it does.

### Actual behavior
The bullet points for PWR, PSEL, and PWM are present, but the I2C is missing.
Although it's pretty typical that cutting the traces for the I2C disables the I2C pullup resistors, I don't have time right now to go through the schematic and verify it (not with the overhead of the new "comment" format), so won't submit a correction myself.

**Comment by SFEMark** [comment]
Thanks for letting us know about this error. Your assumption is correct and it just pulls the SDA/SCL lines to 3.3V (but we all know what happens when you assume). We've updated the Hardware Overview section to add the I2C jumper description to the solder jumpers list.
